main:
  - name: Home
    url: '/'
    weight: 10
  - name: Projects
    url: '/project'
    weight: 20
  - name: Publications
    url: '/publication'
    weight: 30
  - name: Posts
    url: '/post'
    weight: 40
